### ISSUE TITLE
Error: Invalid fixup, adress is neither virtual nor physical

### ISSUE THREAD

**Issue by RasselMartinez** [Zerofour04/FiveM-EmergencyCarPack#2]
There is nothing in the streaming files of the cars??
Which leads to crashes when trying to spawn them on a server.

**Comment by Zerofour04** [comment]
👋 Hey

Thank you for reporting this bug.
I will investigate the problem. This could well be because the pack was used a few months ago and some updates have been released in between.

**Comment by Zerofour04** [comment]
Yep, you're right...

![image](https://user-images.githubusercontent.com/60815764/206878704-d2095ac1-eadd-4f41-bd81-a458e2e7fa0b.png)

**Comment by RasselMartinez** [comment]
Any chance you can reupload them or something like that? :)

**Comment by Zerofour04** [comment]
So the streaming files are in the folders, but I still have to solve the problem of the game crashing 😕

**Comment by Zerofour04** [comment]
Here are some suggested solutions:

> Verify your game file. The collision file (ybn) in the pic is corrupted/improperly done. So remove all mods you have. Verify game files and try.
[Src](https://forum.cfx.re/t/invalid-fixup-address-is-neither-virtual-nor-physical/503524/3?u=zerofour)


> Resolved by clearing the rockstar games appdata folder, and AFTER doing that, doing the verify file integrity utility, i did it without clearing the appdata and that was not working, so i had to wipe it.
[Src](https://forum.cfx.re/t/invalid-fixup-address-is-neither-virtual-nor-physical/881392/4?u=zerofour)

**Comment by Zerofour04** [comment]
Hey,
I found the solution to the problem.  I will upload a BugFix fixes soon.

**Comment by Zerofour04** [comment]
✅ Problem solved by adding an alternative download link
https://github.com/Zerofour04/FiveM-EmergencyCarPack/blob/090ea226fb52b25061eb911f6531cd6911203141/README.md?plain=1#L101
