### ISSUE TITLE
Removal Request

### ISSUE THREAD

**Issue by TheF3nt0n** [Zerofour04/FiveM-EmergencyCarPack#3]
Hello, I am TheF3nt0n. Would you please remove my mods from your pack? I don't want them to be part of it.

To confirm my identity, here is a glimpse of my 5mods screenshot:
![image](https://github.com/Zerofour04/FiveM-EmergencyCarPack/assets/80976950/97a054ac-5336-4325-b8c9-6ddf29c1ef40)

The list of my mods that I demand to be removed:

- [SAMS Speedo Express Ambulance Minipack](https://www.gta5-mods.com/vehicles/sams-speedo-express-ambulance-minipack-vehicles-eup-lore-friendly-add-on)
- [Vapid Speedo Ambulance](https://github.com/Zerofour04/FiveM-EmergencyCarPack/assets/80976950/75ec8f19-f926-4de3-a6e0-db61440684ba) (The mod is no longer on GTA5-Mods anymore, but I still keep the mod in my computer)
- [Buckingham Maverick - 2nd Generation](https://www.gta5-mods.com/vehicles/buckingham-maverick-2nd-generation-add-on-liveries)

**Comment by Zerofour04** [comment]
👋 Hello @TheF3nt0n ,

Thank you for reaching out. I apologize as the owner for including those vehicles in the pack without your consent. I will remove this content promptly.

Best regards,
Ben

**Comment by TheF3nt0n** [comment]
Thank you for cooperation.

Regards,
Fenton
